apiVersion: v1
kind: Service
metadata:
  name: nginx-deploymnet-service
spec:
  selector: nginx-deployment
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
  type: NodePort
