apiVersion: v1
kind: Service
metadata:
  name: liferay-service
spec:
  selector:
    app: liferay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  nodePort: 30000

