apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
        - name: liferay
          image: liferay/portal:7.4.3.86-ga6
          ports:
            - containerPort: 8080

