apiVersion: v1
kind: Service
metadata:
  name: liferay-service
spec:
  selector:
    app: liferay
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort

